# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 11:34
from __future__ import unicode_literals

from django.db import migrations
import mezzanine.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='authors',
            field=mezzanine.core.fields.RichTextField(blank=True, null=True, verbose_name='Authors'),
        ),
    ]
