# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 12:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20150527_1555'),
        ('projects', '0002_auto_20170215_0736'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='related_posts',
            field=models.ManyToManyField(to='blog.BlogPost'),
        ),
    ]
