# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 12:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_related_posts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='related_posts',
            field=models.ManyToManyField(null=True, to='blog.BlogPost'),
        ),
    ]
