# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 12:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20150527_1555'),
        ('projects', '0004_auto_20170215_1222'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectPost',
            fields=[
                ('blogpost_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blog.BlogPost')),
            ],
            options={
                'verbose_name': 'Project post',
                'verbose_name_plural': 'Project posts',
            },
            bases=('blog.blogpost',),
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ('_order',), 'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
        migrations.RemoveField(
            model_name='project',
            name='main_image',
        ),
        migrations.RemoveField(
            model_name='project',
            name='related_posts',
        ),
        migrations.AddField(
            model_name='projectpost',
            name='related_project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='projects.Project'),
        ),
    ]
