# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 09:25
from __future__ import unicode_literals

from django.db import migrations
import mezzanine.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20170215_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='featured_image',
            field=mezzanine.core.fields.FileField(blank=True, max_length=255, null=True, verbose_name='Featured Image'),
        ),
    ]
